### ISSUE TITLE
"photon_noise" socket does not exist error when running example via gui

### ISSUE THREAD

**Issue by samrosegilbert** [fdannert/LIFEsim#24]
I've encountered the following error when following the instructions for [running the example in the LIFEsim API](https://lifesim.readthedocs.io/en/latest/example.html):

```
Traceback (most recent call last):
  File "/Users/samanthagilbert/LIFEsim/lifesim/gui/spectrum_gui.py", line 699, in run_simulation
    self.r_spec, self.flux_p, self.flux_n = self.bus.modules['life'].get_spectrum(
  File "/Users/samanthagilbert/LIFEsim/lifesim/instrument/instrument.py", line 510, in get_spectrum
    noise_bg_list = self.run_socket(s_name='photon_noise',
  File "/Users/samanthagilbert/LIFEsim/lifesim/core/core.py", line 153, in run_socket
    self.socket_exists(s_name=s_name,
  File "/Users/samanthagilbert/LIFEsim/lifesim/core/core.py", line 289, in socket_exists
    raise ValueError('The socket ' + s_name + ' does not exist')
ValueError: The socket photon_noise does not exist
Abort trap: 6
```
When I went to investigate the error in the source code, I noticed that there are lines for adding `photon_noise_star` and `photon_noise_universe` "sockets" but not `photon_noise` in `modules.py`. Similarly, there is no corresponding PhotonNoise class/module for simulating the noise, whereas there is a `PhotonNoiseStarModule` class and a `PhotonNoiseUniverseModule` class. Is it possible that there is a code block and a class missing for `photon_noise` from the `modules.py` script in the `core` folder in the publicly available version of the repo?

Thank you so much!

Samantha
_UW Astro PhD Student_

**Comment by fdannert** [comment]
Dear Samantha,

thank you very much for raising this issue! 
I indeed forgot to update the get_spectrum method in instrument.py to look for the new photon noise classes. I changed this now and everything should work again. Could you please let me know if this issue is also resolved for you with the newest version?

Thank you again and best,
Felix

**Comment by samrosegilbert** [comment]
This update worked! Thank you so much :)
